const aliases = {
    InventoryNo: 'id',
    Category: 'genre',
    CatCode: 'location',
    // OverstockLocation: 'overstock-location',
    // LinkedItemId: 'linked-item-id',
    ArtistFirst: 'first',
    ArtistLast: 'last',
    Title: 'title',
    Label: 'label',
    LabelNo: 'labelNumber',
    Grade: 'grade',
    Speed: 'type',
    Price: 'price',
    Quantity: 'quantity',
    BackupQuantity: 'backups',
    // PotentialQuantity: 'potentialQuantity',
    CoverParts: 'coverParts',
    DiscParts: 'discParts',
    LostBackups: 'lostBackups',
    DateEntered: 'created',
    LastModified: 'modified',
    LastModifiedBy: 'modifiedBy',
    PressingNotes: 'pressingNotes',
    ItemNotes: 'itemNotes',
    internalNotes: 'internalNotes',
    eBayBlacklist: 'ebaySuppress',
    amazonBlacklist: 'amazonSuppress',
    discogsBlacklist: 'discogsSuppress',
    bigPicURL: 'imageUrls',
    clipURL: 'clipUrls',
    discCount: 'discCount',
    ConsignerId: 'consignerId',
    source: 'source',
};

module.exports = aliases;